version: '3.5'

services:

  traefik:
    image: traefik:1.7
    command:
      - --api
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=jackson@cloud-computer.dev
      - --acme.storage=/var/run/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpChallenge.entryPoint=http
      - --docker
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.watch=true
      - --docker.exposedByDefault=false
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  localtunnel-server:
    image: github-computer/localtunnel-server:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:github-computer.app
      - traefik.port=8080

  github-computer:
    image: github-computer/github-computer:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:$GITHUB_USERNAME.github-computer.app
      - traefik.port=8080
