name: Provision Github Cloud Desktop
on: [push]
jobs:
  github-computer:
    runs-on: ubuntu-latest
    container: ghcr.io/sabrehagen/desktop-environment:latest
    steps:
      - name: Start Desktop Environment Remote Access
        run: |
          git clone https://github.com/mxschmitt/action-tmate /opt
          cd /opt/action-tmate
          yarn
          yarn start
          /home/sabrehagen/.config/scripts/startup.sh
          /home/sabrehagen/.yarn/bin/lt --port 8080 --subdomain ${{ github.repository_owner }}
          
