name: Provision Github Cloud Desktop
on: [workflow_dispatch]
jobs:
  github-computer:
    runs-on: ubuntu-latest
    container: ghcr.io/sabrehagen/desktop-environment:latest
    steps:
      - name: Start Desktop Environment Remote Access
        run: |
          /home/sabrehagen/.config/scripts/startup.sh
          ngrok http 80 -authtoken=SrpNTySHG4xFBFfUpAaz_3h2Qdrn33WAXHxUUhuvG1 -region au
