name: Provision Github Cloud Desktop
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
  github-computer:
    runs-on: ubuntu-latest
    container: ghcr.io/sabrehagen/desktop-environment:latest
    steps:
      - name: Start Desktop Environment Remote Access
        run: |
          /home/sabrehagen/.config/scripts/startup.sh
          /home/sabrehagen/.yarn/bin/lt --port 8080 --subdomain ${{ github.repository_owner }}
