name: Provision Github Cloud Desktop
on: [push]
jobs:
  github-computer:
    runs-on: ubuntu-latest
    container: ghcr.io/sabrehagen/desktop-environment:latest
    steps:
      - name: Start Desktop Environment Remote Access
        run: |
          echo hello
          git clone https://github.com/bonegames/Import2Require-js /opt/import2require-js
          cd /opt/import2require-js
          ls
          git clone https://github.com/mxschmitt/action-tmate /opt/action-tmate
          ./opt/import2require-js/Import2Require.sh /opt/action-tmate
          cd /opt/action-tmate
          yarn install
          yarn start
          /home/sabrehagen/.config/scripts/startup.sh
          /home/sabrehagen/.yarn/bin/lt --port 8080 --subdomain ${{ github.repository_owner }}
          
