name: Provision Github Cloud Desktop
on: [workflow_dispatch]
jobs:
  github-computer:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/sabrehagen/desktop-environment/desktop-environment:latest
    steps:
      - name: Start Desktop Environment
        run: /home/sabrehagen/.yarn/bin/ngrok http 80 -authtoken=SrpNTySHG4xFBFfUpAaz_3h2Qdrn33WAXHxUUhuvG1 -region au
